--ALTER TABLE PREDICATEWITHID ADD CONSTRAINT PREDICATEWITHID_pkey PRIMARY KEY (obj, subj, ctx, expl);
-- --CREATE INDEX PREDICATEWITHID_ctx_idx ON PREDICATEWITHID USING btree (ctx);
-- --CREATE INDEX PREDICATEWITHID_expl_idx ON PREDICATEWITHID USING btree (expl);
-- --CREATE INDEX PREDICATEWITHID_obj_idx  ON PREDICATEWITHID  USING btree  (obj);
-- --CREATE INDEX PREDICATEWITHID_obj_subj_idx  ON PREDICATEWITHID  USING btree  (obj, subj);
-- --CREATE INDEX PREDICATEWITHID_subj_idx  ON PREDICATEWITHID  USING btree  (subj);
--CREATE INDEX PREDICATEWITHID_subj_obj_idx  ON PREDICATEWITHID  USING btree  (subj, obj);

ALTER TABLE PREDICATEWITHID ADD CONSTRAINT PREDICATEWITHID_pkey PRIMARY KEY (ctx, obj, subj);
CREATE INDEX PREDICATEWITHID_ctx_subj_obj_idx  ON PREDICATEWITHID  USING btree  (ctx, subj, obj);
CREATE INDEX PREDICATEWITHID_obj_subj_idx  ON PREDICATEWITHID  USING btree  (obj, subj);
CREATE INDEX PREDICATEWITHID_subj_obj_idx  ON PREDICATEWITHID  USING btree  (subj, obj);
--CREATE INDEX PREDICATEWITHID_ctx_idx ON PREDICATEWITHID USING btree (ctx);
--CREATE INDEX PREDICATEWITHID_subj_idx  ON PREDICATEWITHID  USING btree  (subj);
--CREATE INDEX PREDICATEWITHID_obj_idx  ON PREDICATEWITHID  USING btree  (obj);
--CREATE INDEX PREDICATEWITHID_expl_idx ON PREDICATEWITHID USING btree (expl);


